name: Chocolatey Builds

on:
  # Trigger on pushes and on pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# Build on Windows
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build with .Net Framework
      run: .\build.bat -v
    - name: Upload Windows build results
      uses: actions/upload-artifact@v2
      # Always upload build results
      if: ${{ always() }}
      with:
        name: windows-build-results
        path: |
          build_output\build_artifacts\tests\index.html
          build_output\build_artifacts\codecoverage\Html\index.htm
          build_output\_BuildInfo.xml
          build_output\build.log
          code_drop\build_artifacts\ilmerge\ilmerge.log
          code_drop\build_artifacts\ilmerge\ilmergedll.log
    - name: Upload Windows build .nupkg
      uses: actions/upload-artifact@v2
      with:
        name: windows-build-nupkg
        path: code_drop\nuget\*.nupkg
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.linux
          push: false
          tags: chocolatey/choco:latest
